// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.reducerComponent("Page");

function handleAddClick() {
  console.log("clicked! yo");
  return /* () */0;
}

function make(message, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              return React.createElement("div", undefined, React.createElement("h1", undefined, message), React.createElement("p", undefined, "Book:" + state[/* book */0]), React.createElement("p", undefined, "Number Of Books:" + String(state[/* numebrOfBooks */2])), React.createElement("p", undefined, "Name of book:" + state[/* nameOfBook */3]), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(send, /* AddBook */Block.__(0, ["TESTING!"]));
                                })
                            }, "SEND"), React.createElement("button", {
                              onClick: (function () {
                                  return Curry._1(send, /* Increment */0);
                                })
                            }, "ANOTHER LOGGER"), React.createElement("input", {
                              value: state[/* nameOfBook */3],
                              onChange: (function (e) {
                                  return Curry._1(send, /* ChangeInput */Block.__(1, [e.target.value]));
                                })
                            }));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* book */"nothing yet",
                      /* other */"something else",
                      /* numebrOfBooks */0,
                      /* nameOfBook */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                return /* Update */Block.__(0, [/* record */[
                            /* book */state[/* book */0],
                            /* other */state[/* other */1],
                            /* numebrOfBooks */state[/* numebrOfBooks */2] + 1 | 0,
                            /* nameOfBook */state[/* nameOfBook */3]
                          ]]);
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* book */state[/* book */0],
                            /* other */state[/* other */1],
                            /* numebrOfBooks */state[/* numebrOfBooks */2],
                            /* nameOfBook */action[0]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* book */action[0],
                            /* other */state[/* other */1],
                            /* numebrOfBooks */state[/* numebrOfBooks */2],
                            /* nameOfBook */state[/* nameOfBook */3]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  handleAddClick ,
  make ,
  
}
/* component Not a pure module */
